# See the repository:  https://gitlab.v2c2.at/thomasgoelles/vifscience
# The docker image lives on our internal docker registry in gitlab
FROM registry-gitlab.v2c2.at/thomasgoelles/vifscience:py3.8

RUN /opt/conda/bin/pip install sphinx sphinxcontrib-napoleon sphinx_rtd_theme nbsphinx pytest-cov
