# See the repository:  https://gitlab.v2c2.at/thomasgoelles/vifscience
# The docker image lives on our internal docker registry in gitlab
FROM registry-gitlab.v2c2.at/thomasgoelles/vifscience:py3.7_3

RUN pip install laspy