# See the repository:  https://gitlab.v2c2.at/thomasgoelles/vifscience
# The docker image lives on our internal docker registry in gitlab
FROM registry-gitlab.v2c2.at/thomasgoelles/vifscience:py3.8

RUN /opt/conda/bin/pip install sphinx
RUN /opt/conda/bin/pip install sphinxcontrib-napoleon
RUN /opt/conda/bin/pip install sphinx_rtd_theme