# See the repository:  https://gitlab.v2c2.at/thomasgoelles/vifscience
# The docker image lives on our internal docker registry in gitlab
FROM registry-gitlab.v2c2.at/thomasgoelles/vifscience:py3.8

RUN /opt/conda/bin/pip install sphinx sphinxcontrib-napoleon sphinx_rtd_theme nbsphinx pytest-cov sphinx-click

RUN apt-get update \
    && apt-get -y install unzip \
    # Clean up
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
