name: Docker release

#on:
#  push:
#    branches:
#      - "!*"
#    tags:
#      - "v*"

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push tgoelles/pointcloudset
        run:  |
          docker build . --file docker/release.Dockerfile --tag tgoelles/pointcloudset:${{ env.TAG }}
          docker push tgoelles/pointcloudset:${{ env.TAG }}
