name: Docker Image CI

on: [push]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v6.3
      
      - name: Get changed files using a comma separator
        id: changed-files-comma
        uses: tj-actions/changed-files@v6.3
        with:
          separator: ","

      - name: List all added files
        run: |
          for file in "${{ steps.changed-files.outputs.added_files }}"; do
            echo "$file was added"
          done

      - name: Run step when a file changes
        if: contains(steps.changed-files.outputs.modified_files, 'docker/Dockerfile')
        run: |
          echo "Dockerfile has been modified."
          docker build . --file docker/Dockerfile --tag pointcloudset_base:$(date +%s) --target base
          docker build . --file docker/Dockerfile --tag pointcloudset:$(date +%s) --target release
          
