name: Docker Image CI

on: [push]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v6.3

      - name: Get changed files using a comma separator
        id: changed-files-comma
        uses: tj-actions/changed-files@v6.3
        with:
          separator: ","

      - name: List all added files
        run: |
          for file in "${{ steps.changed-files.outputs.added_files }}"; do
            echo "$file was added"
          done

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v6.3
        with:
          files: |
            docker/Dockerfile
            docker/environment.yml

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push tgoelles/pointcloudset_base 
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          docker build . --file docker/Dockerfile --tag tgoelles/pointcloudset_base:latest --target base



