name: Docker base

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        description: "docker tag"
        required: true
        default: "latest"

env:
  image_name: pointcloudset_base

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get the tag name
        if: github.event_name != 'workflow_dispatch'
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: manual tag
        if: github.event_name == 'workflow_dispatch'
        run: echo "TAG=${{ github.event.inputs.name }}" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push tgoelles/pointcloudset
        run: |
          docker build . --file docker/release.Dockerfile --tag tgoelles/${{ env.IMAGE_NAME }}:${{ env.TAG }} --tag tgoelles/${{ env.IMAGE_NAME }}:latest
          docker push tgoelles/${{ env.IMAGE_NAME }}:${{ env.TAG }}
      - name: push latest tag
        if: github.event_name != 'workflow_dispatch'
        run:  docker push tgoelles/pointcloudset:latest