name: Publish to PyPI

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build package
        run: uv run just build-dist

      - name: Publish package
        run: uv run just publish-pypi
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

